http://www.mysqltutorial.org/tryit/query/mysql-case-function/#2

SELECT 
SUM(CASE WHEN DAYOFMONTH(work_day)=1 THEN 1 ELSE 0 END) AS 'day1',
SUM(CASE WHEN DAYOFMONTH(work_day)=2 THEN 1 ELSE 0 END) AS 'day2',
SUM(CASE WHEN DAYOFMONTH(work_day)=3 THEN 1 ELSE 0 END) AS 'day3',
SUM(CASE WHEN DAYOFMONTH(work_day)=4 THEN 1 ELSE 0 END) AS 'day4',
SUM(CASE WHEN DAYOFMONTH(work_day)=5 THEN 1 ELSE 0 END) AS 'day5',
SUM(CASE WHEN DAYOFMONTH(work_day)=6 THEN 1 ELSE 0 END) AS 'day6',
SUM(CASE WHEN DAYOFMONTH(work_day)=7 THEN 1 ELSE 0 END) AS 'day7',
SUM(CASE WHEN DAYOFMONTH(work_day)=8 THEN 1 ELSE 0 END) AS 'day8',
SUM(CASE WHEN DAYOFMONTH(work_day)=9 THEN 1 ELSE 0 END) AS 'day9',
SUM(CASE WHEN DAYOFMONTH(work_day)=10 THEN 1 ELSE 0 END) AS 'day10',
SUM(CASE WHEN DAYOFMONTH(work_day)=11 THEN 1 ELSE 0 END) AS 'day11',
SUM(CASE WHEN DAYOFMONTH(work_day)=12 THEN 1 ELSE 0 END) AS 'day12',
SUM(CASE WHEN DAYOFMONTH(work_day)=13 THEN 1 ELSE 0 END) AS 'day13',
SUM(CASE WHEN DAYOFMONTH(work_day)=14 THEN 1 ELSE 0 END) AS 'day14',
SUM(CASE WHEN DAYOFMONTH(work_day)=15 THEN 1 ELSE 0 END) AS 'day15',
SUM(CASE WHEN DAYOFMONTH(work_day)=16 THEN 1 ELSE 0 END) AS 'day16',
SUM(CASE WHEN DAYOFMONTH(work_day)=17 THEN 1 ELSE 0 END) AS 'day17',
SUM(CASE WHEN DAYOFMONTH(work_day)=18 THEN 1 ELSE 0 END) AS 'day18',
SUM(CASE WHEN DAYOFMONTH(work_day)=19 THEN 1 ELSE 0 END) AS 'day19',
SUM(CASE WHEN DAYOFMONTH(work_day)=20 THEN 1 ELSE 0 END) AS 'day20',
SUM(CASE WHEN DAYOFMONTH(work_day)=21 THEN 1 ELSE 0 END) AS 'day21',
SUM(CASE WHEN DAYOFMONTH(work_day)=22 THEN 1 ELSE 0 END) AS 'day22',
SUM(CASE WHEN DAYOFMONTH(work_day)=23 THEN 1 ELSE 0 END) AS 'day23',
SUM(CASE WHEN DAYOFMONTH(work_day)=24 THEN 1 ELSE 0 END) AS 'day24',
SUM(CASE WHEN DAYOFMONTH(work_day)=25 THEN 1 ELSE 0 END) AS 'day25',
SUM(CASE WHEN DAYOFMONTH(work_day)=26 THEN 1 ELSE 0 END) AS 'day26',
SUM(CASE WHEN DAYOFMONTH(work_day)=27 THEN 1 ELSE 0 END) AS 'day27',
SUM(CASE WHEN DAYOFMONTH(work_day)=28 THEN 1 ELSE 0 END) AS 'day28',
SUM(CASE WHEN DAYOFMONTH(work_day)=29 THEN 1 ELSE 0 END) AS 'day29',
SUM(CASE WHEN DAYOFMONTH(work_day)=30 THEN 1 ELSE 0 END) AS 'day30',
SUM(CASE WHEN DAYOFMONTH(work_day)=31 THEN 1 ELSE 0 END) AS 'day31',
    inn
FROM
    sb_guarding
GROUP BY inn
