version: "3"

services:
  mysql:
    container_name: 'mysql8'
    image: mysql:8.0
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: png
      MYSQL_USER: png
      MYSQL_PASSWORD: png
      
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - 7001:6379
      - 6379:6379

#  docker run -d -p 9980:9980  --name office -e "extra_params=--o:net.service_root=/office --o:ssl.enable=false —o:server_name=localhost:9195" collabora/code:22.05.12.3.1
  collabora:
    container_name: 'collabora-office'
    image: collabora/code:22.05.12.3.1
    environment:
      - extra_params=--o:net.service_root=/office --o:ssl.enable=false —o:server_name=localhost:9195
    ports:
      - 9981:9980
      - 9980:9980

  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ELASTIC_CONTAINER=true
    ports:
      - 9201:9200
      - 9200:9200

  mongodb:
    container_name: 'mongodb'
    image: mongo:5.0.15
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Pass123
    ports:
      - 27018:27017
      - 27017:27017

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 15672:15672
      - 5673:5672
      - 5672:5672

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Pass123
    ports:
      - 5433:5432
      - 5432:5432
      
#  kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

 wiremock:
    image: wiremock/wiremock
    container_name: mywiremock
    command: "--global-response-templating --verbose"
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    ports:
      - 8888:8080
