CREATE TABLE `sb_guarding`  (
`id` int(11) NOT NULL AUTO_INCREMENT,
`create_date` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
`update_date` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0),
PRIMARY KEY (`id`) USING BTREE
)